
-- CREATE USER provider PASSWORD 'provider';
-- GRANT DBA to provider;
-- commit;
-- CREATE SCHEMA provider AUTHORIZATION DBA;
-- SET SCHEMA provider;
-- commit;

-- set hsqldb compatibily modes
-- SET DATABASE SQL SYNTAX DB2 TRUE;
-- SET DATABASE SQL SYNTAX MYS TRUE;
-- SET DATABASE SQL SYNTAX MSS TRUE;
-- SET DATABASE SQL SYNTAX ORA TRUE;
-- SET DATABASE SQL SYNTAX PGS TRUE;
commit;
		
